# Generated by Django 3.2.3 on 2023-03-12 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
